-- CreateTable
CREATE TABLE "final_submissions" (
    "id" TEXT NOT NULL,
    "consumer_name" TEXT NOT NULL,
    "account_no" TEXT NOT NULL,
    "san_load" DOUBLE PRECISION NOT NULL,
    "solar_load" DOUBLE PRECISION NOT NULL,
    "installation_date" TIMESTAMP(3),
    "bidirectional_meter_no" TEXT,
    "bidirectional_meter_cap" TEXT,
    "bidirectional_meter_make" TEXT,
    "bidirectional_meter_multiply_factor" INTEGER,
    "import_kwh" DOUBLE PRECISION,
    "import_kvah" DOUBLE PRECISION,
    "import_mdi" DOUBLE PRECISION,
    "export_kwh" DOUBLE PRECISION,
    "export_kvah" DOUBLE PRECISION,
    "export_mdi" DOUBLE PRECISION,
    "net_solar_meter_no" TEXT,
    "net_solar_meter_cap" TEXT,
    "net_solar_meter_make" TEXT,
    "net_solar_meter_multiply_factor" INTEGER,
    "net_solar_kwh" DOUBLE PRECISION,
    "net_solar_kvah" DOUBLE PRECISION,
    "net_solar_mdi" DOUBLE PRECISION,
    "old_meter_no" TEXT,
    "old_meter_cap" TEXT,
    "old_meter_make" TEXT,
    "old_meter_kwh" DOUBLE PRECISION,
    "old_meter_kvah" DOUBLE PRECISION,
    "old_meter_mdi" DOUBLE PRECISION,

    CONSTRAINT "final_submissions_pkey" PRIMARY KEY ("id")
);
